#!/bin/sh

# REQUIRE: NETWORKING ldconfig syslogd dnstap
# PROVIDE: ipmonitor

. /etc/rc.subr

load_rc_config $name

fail() { echo $@>&2; exit 1; }

test -n "$dnstap_home" || fail "$dnstap_home not defined"
export PYTHONPATH=$dnstap_home/bin:$PYTHON_PATH
test -n "$ipmonitor_home" || fail "ipmonitor_home not specified"
test -n "$ipmonitor_config" || fail "ipmonitor_config not specified"

name="ipmonitor"
pidfile="/var/run/ipmonitor.pid"
command="/usr/sbin/daemon"
command_args="-c -r -t $name -S -T $name -P $pidfile -p $pidfile.child $ipmonitor_home/bin/ipmonitor -c $ipmonitor_config"

export PATH=/usr/local/bin:$PATH

run_rc_command "$1"
