#!/bin/sh

# PROVIDE: ipmonitor

. /etc/rc.subr

fail() { echo @$>&2; exit 1; }

if [ -f /usr/local/etc/ipmonitor.rc ]; then
  . /usr/local/etc/ipmonitor.rc
fi

test -n "$IPMONITOR_HOME" || fail "IPMONITOR_HOME not specified"
ipmonitor=$IPMONITOR_HOME/bin/ipmonitor
test -n "$IPMONITOR_CONFIG" || fail "IPMONITOR_CONFIG not specified"
ipmonitor_config=$IPMONITOR_CONFIG

name="ipmonitor"
pidfile="/var/run/ipmonitor.pid"
command="/usr/sbin/daemon"
command_args="-c -r -t $name -S -T $name -P $pidfile -p $pidfile.child $ipmonitor -c $ipmonitor_config"

export PATH=/usr/local/bin:$PATH

load_rc_config $name
run_rc_command "$1"
