#!/bin/sh

# PROVIDE: ipmonitor
# BEFORE: postfix

. /etc/rc.subr

name="ipmonitor"
pidfile="/var/run/ipmonitor.pid"
command="/usr/sbin/daemon"
export HOME=/home/drew
command_args="-c -r -t $name -S -T $name -P $pidfile /home/drew/ipmonitor/bin/ipmonitor -c /home/drew/.ipmonitor.json"

export PATH=/usr/local/bin:$PATH

load_rc_config $name
run_rc_command "$1"
